### PR TITLE
[A] Added NIST Privacy Framework Mappings

### PR DESCRIPTION
**Pull request by shivasaxena**
Added NIST Privacy Framework to ISO Mappings

### CODE REVIEW

**Comment by alliMSFT** [comment]
Dear Shiva,
Thank you so much for the mapping submission. The data curators and I are reviewing your mapping and will get back to you in case of any question.
All best,
Alex Li

**Comment by alliMSFT** [comment]
Dear Shiva,
Thank you for your patience. The data curators reviewed your proposal and agreed with almost all of your contributions. There are two amendments that we would like to make, however.
First, we propose to map CT.DM-P5 to 7.4.5, 7.4.6, 7.4.8, 8.4.1, and 8.4.2. In other words, we propose to add 7.4.6, 8.4.1 and 8.4.2.
Second, we propose to map PR.DS-P5 to 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 6.10, 6.11, 6.12, and 6.15. All of your proposed items are inclusive of the above. But we think it makes sense to add most of clause 6 because NIST's understanding of data leak is rather comprehensive.
If you can agree to these adjustments, we can incorporate them into the project shortly. Please let us know what you think. We can also meet over a call if you see fit.
All best,
Alex

**Comment by shivasaxena** [comment]
Hi Alex,

I reviewed the sections mentioned by you, and agree with the comments. You can make the changes and merge the request.

I would be glad to get in touch with the team.

As my next steps I was thinking of adding country specific GDPR implementations like UK Data Protection Act and France CNIL to start with into the project, but am slightly not sure how we want to structure them, like should we include them in the GDPR section or have one separate section for each county. We can co-ordinate this over mail/github issue or have a call based on your availability, else you can always discuss it in the next monthly meeting I would review them when its available in the repository.

And thanks to the team for reviewing the commit.

--
Best regards
Shiva Saxena

**Review by mkslalom — APPROVED** [review]
Thank you.

**Comment by alliMSFT** [comment]
Hi Shiva,

Before I merge your pull request, I want to confirm why you have two separate pull requests. The pull request we are on "Added NIST Privacy Framework Mappings #9" already seems to contain the node dependency update we need. I'm not sure what the other pull request does.

As to EU member states and UK variations on GDPR, I think it is better to structure them separately. This will allow us to compare the difference between member states. Work wise, it is not too difficult since you can duplicate the GDPR mapping content and edit the delta.

Since you have no dispute over the suggested changes, I think we can continue to correspond over GitHub to spare one of us working at late hours to chat given the time zone difference between India and Seattle.

All best,
Alex

**Comment by shivasaxena** [comment]
Hi Alex,

The idea was to have one commit per change, so I committed one for node and one for the data mapping update. Then I merged the node updates to my master and so the node updates are showing updates here too.

You can merge this change and close the other marked as already merged.
Moving forward I'll keep my master branch separate and have one branch per commit.

--
Best regards
Shiva Saxena

**Pull request merged**
